apiVersion: apps/v1
kind: Deployment
metadata:
  name: appvolumes-busybox-multitool
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: busybox
          image: busybox:1.28
          command: [ "sh", "-c", "while [ true ]; do echo 'Writing logs now..'; sleep 5; done | tee -a /mnt/testfolder/logs.txt" ]
          volumeMounts:
              - name: testvolume
                mountPath: /mnt/testfolder
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
        - name: multitool
          image: wbitt/network-multitool
          command: ['sh', '-c', 'echo "The logs is running!" && tail -f /mnt/testfolder/logs.txt' ]
          volumeMounts:
              - name: testvolume
                mountPath: /mnt/testfolder
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: testvolume
          persistentVolumeClaim:
            claimName: mypvc
