apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc-sc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
